# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaInv <- function(x) {
    .Call('_SQBiT_armaInv', PACKAGE = 'SQBiT', x)
}

cppkp <- function(a, b) {
    .Call('_SQBiT_cppkp', PACKAGE = 'SQBiT', a, b)
}

eigenMatMult <- function(A, B) {
    .Call('_SQBiT_eigenMatMult', PACKAGE = 'SQBiT', A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call('_SQBiT_eigenMapMatMult', PACKAGE = 'SQBiT', A, B)
}

eigenMapMatMult2 <- function(A, B, n_cores) {
    .Call('_SQBiT_eigenMapMatMult2', PACKAGE = 'SQBiT', A, B, n_cores)
}

neg <- function(x) {
    .Call('_SQBiT_neg', PACKAGE = 'SQBiT', x)
}

sum_cpp <- function(x) {
    .Call('_SQBiT_sum_cpp', PACKAGE = 'SQBiT', x)
}

sum_rhotau <- function(x, tau) {
    .Call('_SQBiT_sum_rhotau', PACKAGE = 'SQBiT', x, tau)
}

arma_dist <- function(X) {
    .Call('_SQBiT_arma_dist', PACKAGE = 'SQBiT', X)
}

